### PR TITLE
Make Dialogue Skippable

### PR DESCRIPTION
**Pull request by MasterTrainerPK**
- "typer elements" in the majority of the puzzle levels are now skippable
- minor bug fix involving color changes

### CODE REVIEW

**Review by Ilovemyhous — CHANGES_REQUESTED** [review]
Hello!
Thanks for the help!
There are still some minor issues, like on level 1 and 2, where two lines are played at the same time.
The audio should also be stopped when skipping the text, but if you want, I can look at that myself.
Also, before merging the code, could you please change the version to 0.1.4, and eventually putting the changes in the changelog if you want.

**Review by Ilovemyhous — COMMENTED** [review]
Seems good! 👍
I’ll try it out later today.

**Comment by MasterTrainerPK** [comment]
It still has the sound issue I imagine, but I haven't been able to consistently get the sound working ever, so I'll leave that issue to u.
sry 4 that.

**Review by Ilovemyhous — APPROVED** [review]
Changes approved!
Thanks for your help! ❤️

**Pull request merged**
